development:
  smtp_default_from: 'noreply@shareproz.development.com'
  smtp_default_host: 'localhost:3000'
  smtp_domain: 'sparknet.me'
  smtp_address: 'email-smtp.us-east-1.amazonaws.com'
  smtp_port: 587
  smtp_username: 'AKIAIUNHKVQDFEMY66LA'
  smtp_password: 'AtG/OGNDMHgw1YR6mbPJN9m11h0Ij1yQdqxYTg0DT4fw'
  support_email: 'support@sparknet.development.me'
  smtp_default_feedback: 'feedback@sparknet.xyz'
  base_url: 'http://localhost:3000'
  gcm_key: 'AIzaSyDKZ3NFCIOaD7EuFnWZ_zwkMkVfqMD4Auk'
  apple_push_certificate_file: 'apple_push_notification.pem'
  s3_bucket: 'shareproz-files-production'
  s3_access_key_id: 'AKIAJAZVYX5ACMRTP3ZA'
  s3_secret_access_key: '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'
  ios_link: 'http://apple.com'
  android_link: 'http://google.com'
test:
  smtp_default_from: 'noreply@shareproz.test.com'
  smtp_default_host: 'localhost:3000'
  smtp_domain: 'sparknet.me'
  smtp_address: 'email-smtp.us-east-1.amazonaws.com'
  smtp_port: 587
  smtp_username: 'AKIAIUNHKVQDFEMY66LA'
  smtp_password: 'AtG/OGNDMHgw1YR6mbPJN9m11h0Ij1yQdqxYTg0DT4fw'
  support_email: 'support@sparknet.test.me'
  smtp_default_feedback: 'feedback@sparknet.xyz'
  base_url: 'http://localhost:3000'
  gcm_key: 'AIzaSyDKZ3NFCIOaD7EuFnWZ_zwkMkVfqMD4Auk'
  apple_push_certificate_file: 'apple_push_notification.pem'
  s3_bucket: 'shareproz-files-dev'
  s3_access_key_id: 'AKIAI37DPNLOSZDY5FUA'
  s3_secret_access_key: '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'
  ios_link: 'http://apple.com'
  android_link: 'http://google.com'
staging: &staging
  smtp_default_from: 'email@sparknet.me'
  smtp_default_host: 'shareproz.sparknet.me'
  smtp_domain: 'sparknet.me'
  smtp_address: 'email-smtp.us-east-1.amazonaws.com'
  smtp_port: 587
  smtp_username: 'AKIAIUNHKVQDFEMY66LA'
  smtp_password: 'AtG/OGNDMHgw1YR6mbPJN9m11h0Ij1yQdqxYTg0DT4fw'
  support_email: 'support@sparknet.me'
  base_url: 'http://wingmate.co'
  log_facility: 'shareproz-staging'
  smtp_default_feedback: 'feedback@sparknet.xyz'
  gcm_key: 'AIzaSyDKZ3NFCIOaD7EuFnWZ_zwkMkVfqMD4Auk'
  apple_push_certificate_file: 'apple_push_notification.pem'
  s3_bucket: 'shareproz-files-staging'
  s3_access_key_id: 'AKIAI37DPNLOSZDY5FUA'
  s3_secret_access_key: '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'
  ios_link: 'http://apple.com'
  android_link: 'http://google.com'
stagingdeploy: *staging

production: &production
  smtp_default_from: 'info@shareproz.com'
  smtp_default_host: 'app.shareproz.com'
  smtp_domain: 'shareproz.com'
  smtp_address: 'email-smtp.us-east-1.amazonaws.com'
  smtp_port: 587
  smtp_username: 'AKIAI2VVHWPOI2R5YLPA'
  smtp_password: 'AvuapimhFJevinqWBtNDUYoCb54xmQJues/3cdIXZqLm'
  support_email: 'support@sparknet.me'
  base_url: 'http://app.shareproz.com'
  log_facility: 'shareproz-production'
  smtp_default_feedback: 'feedback@shareproz.com'
  gcm_key: 'AIzaSyDKZ3NFCIOaD7EuFnWZ_zwkMkVfqMD4Auk'
  apple_push_certificate_file: 'apple_dev_push_notification.pem'
  s3_bucket: 'shareproz-files-production'
  s3_access_key_id: 'AKIAJAZVYX5ACMRTP3ZA'
  s3_secret_access_key: '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'
  ios_link: 'http://apple.com'
  android_link: 'http://google.com'
productiondeploy: *production
