---
- !ruby/object:Rubber::Configuration::InstanceItem
  name: production
  domain: foo.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: apache
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: passenger
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: common
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mysql
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mysql_master
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: elasticsearch
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: examples
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graphite_server
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graphite_web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_elasticsearch
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_mongodb
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mongodb
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_server
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: haproxy
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web_tools
    options: {}
  instance_id: i-052e745c3ea1b08f9
  image_type: c1.medium
  image_id: ami-20800c10
  security_groups:
  - default
  - web
  - web_tools
  zone: us-west-2a
  network: 
  gateway: 
  external_host: ec2-35-161-193-148.us-west-2.compute.amazonaws.com
  external_ip: 35.161.193.148
  internal_host: ip-172-31-19-46.us-west-2.compute.internal
  internal_ip: 172.31.19.46
  provider: aws
  platform: linux
  root_device_type: ebs
- !ruby/object:Rubber::Configuration::InstanceItem
  name: wingmateapp.co
  domain: wingmateapp.co
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: apache
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: passenger
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: common
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mysql
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mysql_master
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: elasticsearch
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: examples
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graphite_server
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graphite_web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_elasticsearch
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_mongodb
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mongodb
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_server
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: haproxy
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web_tools
    options: {}
  instance_id: i-04a7c5ca09a29aee1
  image_type: c1.medium
  image_id: ami-20800c10
  security_groups:
  - default
  - web
  - web_tools
  zone: us-west-2a
  network: 
  gateway: 
  external_host: ec2-35-162-91-205.us-west-2.compute.amazonaws.com
  external_ip: 35.162.91.205
  internal_host: ip-172-31-21-43.us-west-2.compute.internal
  internal_ip: 172.31.21.43
  provider: aws
  platform: linux
  root_device_type: ebs
- !ruby/object:Rubber::Configuration::InstanceItem
  name: wingmate.co
  domain: foo
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: apache
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: passenger
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: common
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mysql
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mysql_master
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: elasticsearch
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: examples
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graphite_server
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graphite_web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_elasticsearch
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_mongodb
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mongodb
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_server
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: haproxy
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web_tools
    options: {}
  instance_id: i-0ac0fd63f9c0fe28f
  image_type: c1.medium
  image_id: ami-20800c10
  security_groups:
  - default
  - web
  - web_tools
  zone: us-west-2a
  network: 
  gateway: 
  external_host: ec2-35-161-126-209.us-west-2.compute.amazonaws.com
  external_ip: 35.161.126.209
  internal_host: ip-172-31-29-126.us-west-2.compute.internal
  internal_ip: 172.31.29.126
  provider: aws
  platform: linux
  root_device_type: ebs
- !ruby/object:Rubber::Configuration::InstanceItem
  name: wingmateapp prod
  domain: foo
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: apache
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: passenger
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: common
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mysql
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mysql_master
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: elasticsearch
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: examples
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graphite_server
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graphite_web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_elasticsearch
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_mongodb
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mongodb
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_server
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: haproxy
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web_tools
    options: {}
  instance_id: i-02710edef8c42e7b2
  image_type: c1.medium
  image_id: ami-20800c10
  security_groups:
  - default
  - web
  - web_tools
  zone: us-west-2a
  network: 
  gateway: 
  external_host: ec2-35-162-119-73.us-west-2.compute.amazonaws.com
  external_ip: 35.162.119.73
  internal_host: ip-172-31-30-249.us-west-2.compute.internal
  internal_ip: 172.31.30.249
  provider: aws
  platform: linux
  root_device_type: ebs
- !ruby/object:Rubber::Configuration::InstanceItem
  name: wingmate app
  domain: foo
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: apache
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: passenger
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: common
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mysql
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mysql_master
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: elasticsearch
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: examples
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graphite_server
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graphite_web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_elasticsearch
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_mongodb
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mongodb
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_server
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: haproxy
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web_tools
    options: {}
  instance_id: i-0d63777376204021d
  image_type: c1.medium
  image_id: ami-20800c10
  security_groups:
  - default
  - web
  - web_tools
  zone: us-west-2a
  network: 
  gateway: 
  external_host: ec2-35-162-10-59.us-west-2.compute.amazonaws.com
  external_ip: 35.162.10.59
  internal_host: ip-172-31-29-52.us-west-2.compute.internal
  internal_ip: 172.31.29.52
  provider: aws
  platform: linux
  root_device_type: ebs
- !ruby/object:Rubber::Configuration::InstanceItem
  name: wingmateapp
  domain: wingmateapp.co
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: apache
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: passenger
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: common
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mysql
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mysql_master
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: elasticsearch
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: examples
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graphite_server
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graphite_web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_elasticsearch
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_mongodb
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mongodb
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_server
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: haproxy
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web_tools
    options: {}
  instance_id: i-01a3738ac01dfdaca
  image_type: m1.small
  image_id: ami-26d87c46
  security_groups:
  - default
  - web
  - web_tools
  zone: us-west-2b
  network: 
  gateway: 
  external_host: ec2-35-160-251-81.us-west-2.compute.amazonaws.com
  external_ip: 35.160.251.81
  internal_host: ip-172-31-44-239.us-west-2.compute.internal
  internal_ip: 172.31.44.239
  provider: aws
  platform: linux
  root_device_type: ebs
- !ruby/object:Rubber::Configuration::InstanceItem
  name: wingmateapp production
  domain: wingmateapp.co
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: apache
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: passenger
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: common
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mysql
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mysql_master
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: elasticsearch
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: examples
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graphite_server
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graphite_web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_elasticsearch
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_mongodb
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mongodb
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_server
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: haproxy
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web_tools
    options: {}
  instance_id: i-0c8f1b9dbd9606ed0
  image_type: m1.small
  image_id: ami-26d87c46
  security_groups:
  - default
  - web
  - web_tools
  zone: us-west-2b
  network: 
  gateway: 
  external_host: ec2-35-161-66-245.us-west-2.compute.amazonaws.com
  external_ip: 35.161.66.245
  internal_host: ip-172-31-40-35.us-west-2.compute.internal
  internal_ip: 172.31.40.35
  provider: aws
  platform: linux
  root_device_type: ebs
- volumes: {}
  static_ips: {}
  vpc: {}
